### ISSUE TITLE
Login attempt via ORCID causes error

### ISSUE THREAD

**Issue by jweile** [VariantEffect/mavedb#148]
After clicking the login button and signing into ORCID, I am redirected to https://www.mavedb.org/profile/error/ stating

"ORCID Authentication Error
Oh no! Your account could not be created. Try registering again, or contact support for help."

```Authentication failed: HTTPSConnectionPool(host='orcid.org', port=443): Max retries exceeded with url: /oauth/token (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f010c99a2b0>: Failed to establish a new connection: [Errno -2] Name or service not known',))```

**Comment by afrubin** [comment]
@jweile I just tried to log in and was successful. I can also see your user record so it doesn't seem like it was deleted or anything.

Would you please try again and let us know how it goes?

**Comment by jweile** [comment]
@afrubin Thank you! I tried again this morning and it seems to work now.  

This makes the problem difficult to debug of course :( . We'll have to see if the problem ever comes up again.

Thanks again!
