### ISSUE TITLE
API support for optional keys

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/MaveDB#186]
The MaveTools upload toolkit throws an error when all of the optional metadata isn't present (e.g. UniProt identifier, metadata blob).

These should be considered optional and the MaveTools upload toolkit should have the correct default values that the API is expecting when they are absent.

**Comment by EstelleDa** [comment]
Sorry I didn't notice you post this problem so many days ago. 
Branch is https://github.com/VariantEffect/MaveDB/tree/fixApiBug
