### ISSUE TITLE
Upload fails with UTF-8 byte ordering marks

### ISSUE THREAD

**Issue by genomematt** [VariantEffect/MaveDB#192]
Some versions of excel generated csv files contain a byte ordering mark that creates an invalid heading name (eg \ufeffhgvs_pro)

Files should be opened with a utf-8-sig decoder to avoid this issue

**Comment by genomematt** [comment]
This issue manifests as a persistent "Your Score file must define either a nucleotide hgvs column 'hgvs_nt' or a protein hgvs column 'hgvs_pro'. Columns are case-sensitive and must be comma delimited." error when the file appears correct when opened in a plain text editor. Included here for search purposes.

A work around for this issue is to select "Comma Separated Values (.csv)" as the saved file type in Excel rather than the default CSV UTF-8 format

**Comment by afrubin** [comment]
@harmatt Please make sure that this is caught and that there's a suitable test case for this in the MaveCore validation test suite.

**Comment by afrubin** [comment]
Migrated to https://github.com/VariantEffect/mavedb-api/issues/106
