### ISSUE TITLE
Two experiments with same URN?

### ISSUE THREAD

**Issue by ijhoskins** [VariantEffect/MaveDB#197]
I just published a dataset and am seeing an issue with the following experiment:
https://www.mavedb.org/#/experiments/urn:mavedb:00000661-c

It looks like there are two score sets, and when I try to access them I see:
```
Page Not Found
The requested score set does not exist.
```

These scores should really be within two different experiments. I believe I had chosen a separate experiment when creating the new score sets.

If view which experiments are in the Experiment Set, I see two experiments with the same URN. Perhaps the issue is not with the score sets but with experiments having the same URN?

**Comment by ashsny** [comment]
We've fixed this by manually editing the experiments' URNs to be unique. We will make a change to enforce uniqueness of URNs at publish time and add alerting to the dev team for the 500s this generated. Unfortunately, we weren't able to tell how this occurred (it seems like the publish requests were non-overlapping).

**Comment by ashsny** [comment]
Just kidding, I did figure out how this occurred: https://github.com/VariantEffect/mavedb-api/issues/97.

**Comment by ijhoskins** [comment]
Thanks @ashsny things look good for the Experiment set now!
