### ISSUE TITLE
MaveVis integration

### ISSUE THREAD

**Issue by afrubin** [VariantEffect/mavedb#42]
@jweile What are the requirements for viewing a ScoreSet in MaveVis?

If someone has a UniProt ID and offset with their ScoreSet can we add a "View in MaveVis" or similar button to the ScoreSet page, and if so what is the format of the URL?

The button should launch in a new page/new tab by default.

**Comment by jweile** [comment]
The feature has now been pushed to the cloud instance, and now also uses the updated URN scheme: 
http://varianteffect.com/?ssid=urn:mavedb:00000001-a-1

When you try this, you may need to clear your browser cache to make sure the browser loads the latest version of the page.

The server syncs with MaveDB every 5 minutes, so newly uploaded/published scoresets would take up to 5 minutes to be linkable.

**Comment by afrubin** [comment]
This is so cool. We will add a button to the Score Set pages that have UniProt information that links out. What do you want the button to say? MaveVis?

**Comment by daniaki** [comment]
Upcoming in the next mavedb update:

![mavevis](https://user-images.githubusercontent.com/7043686/42075845-298d3872-7bb6-11e8-8484-7171e0796cdf.png)

If you have a MaveVis logo with alpha transparency we could use that as the button icon.

**Comment by jweile** [comment]
Awesome! 

We'll have to brainstorm about logos. For now I was using this:
![image](https://user-images.githubusercontent.com/31638122/42098395-c99ca77c-7b88-11e8-87d6-8c7e33224a3e.png)

But that's more supposed to be site-wide logo that will serve as an umbrella for all the different tools we'll be developing in the future. 

Some other versions I have been playing around with:
![image](https://user-images.githubusercontent.com/31638122/42098780-dd8fa6b6-7b89-11e8-8402-f4dc27eeb6b8.png)

![image](https://user-images.githubusercontent.com/31638122/42098809-eff4b90e-7b89-11e8-840f-f40c1bc97645.png)
