### ISSUE TITLE
Q/R-Component support

### ISSUE THREAD

**Issue by daniaki** [VariantEffect/MaveDB#75]
Optional component support when requesting a URN resource as documented [here](https://tools.ietf.org/html/rfc8141#section-2.3):
 - [r-components](https://tools.ietf.org/html/rfc8141#section-2.3.1)
 - [q-components](https://tools.ietf.org/html/rfc8141#section-2.3.2)
 - [f-components](https://tools.ietf.org/html/rfc8141#section-2.3.3)

This will allow passing of additional information such as authorization tokens when requesting a URN via API as an alternate method to storing tokens in the authorization header.

**Comment by afrubin** [comment]
Migrated to https://github.com/VariantEffect/mavedb-api/issues/107
