### ISSUE TITLE
Switch to using biocommons hgvs package for variant validation

### ISSUE THREAD

**Issue by daniaki** [VariantEffect/mavedb#78]
Maveric will need to use the [biocommons hgvs](https://github.com/biocommons/hgvs) package in order to perform variant mapping from cDNA to genomic coordinates. MaveDB should switch the validation backend to [biocommons hgvs](https://github.com/biocommons/hgvs) as well for consistency and for future utility.

**Comment by afrubin** [comment]
Instead of [biocommons hgvs](https://github.com/biocommons/hgvs), we should look into using the [GA4GH Variation Representation Specification](https://vr-spec.readthedocs.io/en/1.0/). They have a reference Python implementation that is sufficiently developed to start prototyping.

**Comment by afrubin** [comment]
We've decided to move forward using our own MAVE-HGVS implementation.
